{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sample-tenant-app.fullname" . }}
  labels:
    {{- include "sample-tenant-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sample-tenant-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scheme: http
{{- end }}
