apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPinWIServiceAccount
metadata:
  name: pin-wi-to-namespace
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ServiceAccount"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - cert-manager
      - argocd
