###############################################################################
# Outputs — copy these into environments/dev/terraform.tfvars after apply.
# `terraform output -json` dumps the full set; the bootstrap README has the
# exact one-liner.
###############################################################################

output "project_id" {
  description = "The newly-created project."
  value       = google_project.this.project_id
}

output "project_number" {
  description = "Numeric project number — needed for some IAM bindings."
  value       = data.google_project.this.number
}

output "region" {
  description = "Region this trial runs in."
  value       = var.region
}

output "network_self_link" {
  description = "VPC self-link to pass to modules/gke-hardened."
  value       = google_compute_network.vpc.self_link
}

output "subnetwork_self_link" {
  description = "Subnet self-link with secondary ranges for Pods + Services."
  value       = google_compute_subnetwork.dev.self_link
}

output "pods_secondary_range_name" {
  description = "Name of the Pods secondary range."
  value       = google_compute_subnetwork.dev.secondary_ip_range[0].range_name
}

output "services_secondary_range_name" {
  description = "Name of the Services secondary range."
  value       = google_compute_subnetwork.dev.secondary_ip_range[1].range_name
}

output "master_ipv4_cidr_block" {
  description = "/28 reserved for the private GKE control plane."
  value       = var.master_ipv4_cidr_block
}

output "database_encryption_key" {
  description = "KMS key for etcd CMEK."
  value       = google_kms_crypto_key.etcd.id
}

output "boot_disk_kms_key" {
  description = "KMS key for node boot disks."
  value       = google_kms_crypto_key.nodes.id
}

output "backup_encryption_key" {
  description = "KMS key for Backup for GKE."
  value       = google_kms_crypto_key.backup.id
}

output "tfstate_bucket" {
  description = "GCS bucket the cluster + platform stacks should use as their backend."
  value       = google_storage_bucket.tfstate.name
}

output "bastion_name" {
  description = "Bastion VM name."
  value       = google_compute_instance.bastion.name
}

output "bastion_zone" {
  description = "Bastion VM zone."
  value       = google_compute_instance.bastion.zone
}

# Convenience: print the master_authorized_networks entry the cluster
# stack will need. Bastion's internal IP is enough because the cluster
# control plane is private and the bastion is inside the same VPC.
output "master_authorized_networks_hint" {
  description = "Paste into environments/dev/terraform.tfvars as master_authorized_networks."
  value = [
    {
      cidr_block   = "${google_compute_instance.bastion.network_interface[0].network_ip}/32"
      display_name = "bastion"
    },
  ]
}

# Final, copy-pasteable .tfvars chunk for the cluster stack.
output "cluster_tfvars_snippet" {
  description = "Drop this into environments/dev/terraform.tfvars after `terraform apply` here."
  value       = <<-EOT

    # ─── generated by environments/dev-bootstrap on ${formatdate("YYYY-MM-DD", timestamp())} ───
    project_id           = "${google_project.this.project_id}"
    region               = "${var.region}"
    network_self_link    = "${google_compute_network.vpc.self_link}"
    subnetwork_self_link = "${google_compute_subnetwork.dev.self_link}"

    pods_secondary_range_name     = "${google_compute_subnetwork.dev.secondary_ip_range[0].range_name}"
    services_secondary_range_name = "${google_compute_subnetwork.dev.secondary_ip_range[1].range_name}"

    master_ipv4_cidr_block = "${var.master_ipv4_cidr_block}"

    master_authorized_networks = [
      {
        cidr_block   = "${google_compute_instance.bastion.network_interface[0].network_ip}/32"
        display_name = "bastion"
      },
    ]

    database_encryption_key = "${google_kms_crypto_key.etcd.id}"
    boot_disk_kms_key       = "${google_kms_crypto_key.nodes.id}"

    enable_backup         = true
    backup_encryption_key = "${google_kms_crypto_key.backup.id}"
  EOT
}

###############################################################################
# GitHub Actions Workload Identity Federation
###############################################################################

output "github_wif_provider" {
  description = "Workload Identity Pool provider — paste into terraform-plan.yml / terraform-apply.yml as `workload_identity_provider`."
  value       = module.github_wif.provider_resource_name
}

output "github_wif_service_account" {
  description = "Service account email the WIF identity impersonates. Paste into the same workflow's `service_account`."
  value       = module.github_wif.service_account_email
}

output "github_wif_plan_provider" {
  description = "Read-only Workload Identity Pool provider for PR-time plan workflows. Lower trust than the apply provider — distinct pool, distinct SA, refs scoped to PR refs."
  value       = module.github_wif_plan.provider_resource_name
}

output "github_wif_plan_service_account" {
  description = "Service account email for the read-only plan identity."
  value       = module.github_wif_plan.service_account_email
}

output "github_actions_secrets" {
  description = "Repository-level Actions variables the operator sets once after the first apply. Two pairs: apply (main only, write) + plan (PR refs, read-only)."
  value       = <<-EOT

    # ─── set as repository VARIABLES (not secrets — these aren't secret) ───
    gh variable set GCP_PROJECT_ID         --body "${google_project.this.project_id}"
    gh variable set GCP_REGION             --body "${var.region}"
    gh variable set GCP_TFSTATE_BUCKET     --body "${google_storage_bucket.tfstate.name}"
    gh variable set CLUSTER_NAME           --body "idp-dev"

    # Apply identity (main only, write)
    gh variable set GCP_WIF_PROVIDER       --body "${module.github_wif.provider_resource_name}"
    gh variable set GCP_TERRAFORM_SA       --body "${module.github_wif.service_account_email}"

    # Plan identity (PR refs, read-only)
    gh variable set GCP_WIF_PLAN_PROVIDER  --body "${module.github_wif_plan.provider_resource_name}"
    gh variable set GCP_TERRAFORM_PLAN_SA  --body "${module.github_wif_plan.service_account_email}"
  EOT
}

